### ISSUE TITLE
Allow styling select input color

### ISSUE THREAD

**Issue by simPod** [uber/baseweb#3158]
## Feature description

![image](https://user-images.githubusercontent.com/327717/78296579-45e80380-752e-11ea-9205-a1b0b10fd174.png)

The color for Select input cannot be styled through BaseWeb

Currently, I have to use

```css
[data-baseweb="select"] input {
    color: white;
}
```
